Description: >
  This simple cloudformation template for hosting static website using S3 Bucket.
  Domain is registered on another domain registrar.
  Make sure update NS Entries on your domain registrar.
  This will use Public Hosted Zone.

Parameters:
  DomainName:
    Description: Valid Domain Name. (eg. example.com)
    Type: String
    AllowedPattern: ^[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]\.[a-zA-Z]{2,}$
    ConstraintDescription: Value must contain valid domain
  RegionId:
    Description: Region
    Type: String
    Default: "ap-southeast-1"
  RegionHostedZoneId:
    Description: Hosted zone region Id
    Type: String
    Default: Z3O0J2DXBE1FTB 
  TTL:
    Description: TTL
    Type: String
    Default: 300
  IndexDocument:
    Description: Index html file (eg. index.html)
    Type: String
    Default: "index.html"
  ErrorDocument:
    Description: Error html file (eg. error.html)
    Type: String
    Default: "error.html"

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties: 
      Name: !Ref DomainName
      
  ARecordtoS3:
    Type: AWS::Route53::RecordSet
    DependsOn:
      - HostedZone
    Properties: 
      Name: !Ref DomainName
      Type: A
      HostedZoneId: !Ref HostedZone
      AliasTarget: 
        DNSName: !Sub "s3-website-${RegionId}.amazonaws.com"
        HostedZoneId: !Ref RegionHostedZoneId
  
  StaticBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      WebsiteConfiguration:
        IndexDocument: !Ref IndexDocument
        ErrorDocument: !Ref ErrorDocument
      
  StaticBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn:
      - StaticBucket
    Properties: 
      Bucket: !Ref StaticBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: 
              - "s3:GetObject"
            Resource: !Sub "${StaticBucket.Arn}/*"

Outputs:
  HostedZoneId:
    Value: !Ref HostedZone
    Export:
      Name: !Sub '${AWS::StackName}-HostedZoneId'
  StaticBucketArn:
    Value: !GetAtt StaticBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'
